services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smile-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-smile}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smile_secure_password}
      POSTGRES_DB: ${POSTGRES_DB:-smile_insurance}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-smile}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for sessions and caching
  redis:
    image: redis:7-alpine
    container_name: smile-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-smile_redis_password}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smile-web
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER:-smile}:${POSTGRES_PASSWORD:-smile_secure_password}@postgres:5432/${POSTGRES_DB:-smile_insurance}
      
      # Redis
      REDIS_URL: redis://:${REDIS_PASSWORD:-smile_redis_password}@redis:6379
      
      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-change_this_to_a_random_secret_in_production}
      
      # App Config
      NODE_ENV: production
      
      # Desktop sync endpoint (internal)
      SMILE_SYNC_USERS_URL: http://web:3000/api/desktop/users
    ports:
      - "${WEB_PORT:-3000}:3000"
    volumes:
      - uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (optional but recommended)
  nginx:
    image: nginx:alpine
    container_name: smile-nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  uploads:
    driver: local
  nginx_cache:
    driver: local

networks:
  default:
    name: smile-network
