export const ROUTES = {
  user: {
    dashboard: "/user/dashboard",
    card: "/user/dashboard/card",
    claimSubmit: "/user/dashboard/claims/submit",
    family: "/user/dashboard/family",
    payments: "/user/dashboard/payments",
  },
  staff: {
    visitors: "/staff/visitors",
    enquiryNew: "/staff/enquiries/new",
    memberCreate: "/staff/members/create",
    members: "/staff/members",
    insuranceCards: "/staff/insurance-cards",
    claims: "/staff/claims",
    claimsSubmit: "/staff/claims/submit",
    underwriting: "/staff/underwriting",
    payments: "/staff/payments",
    chat: "/staff/chat",
    contacts: "/staff/contacts",
    invoices: "/staff/invoices",
    files: "/staff/files",
    companies: "/staff/companies",
    hr: "/staff/hr",
    inventory: "/staff/inventory",
    reports: "/staff/reports",
    settings: "/staff/settings",
    motor: "/staff/motor",
    motorSignup: "/staff/motor/signup",
    medical: "/staff/medical",
  },
  admin: {
    memberCreate: "/admin/members/create",
    claimsSubmit: "/admin/claims/submit",
    companiesCreate: "/admin/companies/create",
    companiesList: "/admin/companies",
    features: "/admin/settings/features",
  },
}
